name: pr

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  pr-title:
    uses: MdaaaaO/conventional-release/.github/workflows/pr-title.yml@v0
